services:
  - type: web
    name: video-content-moderation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads
      chmod 777 uploads
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    plan: free
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: video-storage
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    build:
      includePaths:
        - models/
        - uploads/ 
