services:
  - type: web
    name: video-content-moderation
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    plan: free  # Change to 'starter' or 'standard' for better performance
    healthCheckPath: /
    autoDeploy: true 