services:
  - type: web
    name: video-moderation-v2
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import os; os.makedirs('uploads', exist_ok=True)"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    plan: free
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: video-storage-v2
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    build:
      includePaths:
        - models/
        - uploads/ 
